Repository JAStrachan/AC41004-Team-12-W3rld, pull requests merged in 2018-09, with the labels that each got.

#22 Basic card that has basic verisons of the features
  CSS/cardstyle.css
  CSS/stylesheet.css
  JS/card.js
  JS/graph.js
  SVG/humidity.svg
  SVG/thermometer.svg
  index.html
Labels: enhancement

#27 Added custom markers and other improvements
  CSS/cardstyle.css
  CSS/marker.css
  JS/card.js
  JS/graph.js
  JS/loadingData.js
  JS/marker.js
  JSON/TemperatureDataKelvin.json
  SVG/humidity.svg
  favicon.ico
  index.html
Labels: enhancement

#26 Fixed some weird css for the card
  CSS/cardstyle.css
  JS/card.js
Labels: enhancement

#31 Slider
  JS/card.js
  JS/marker.js
  JSON/TemperatureDataKelvin.json
  SVG/humidity.svg
  SVG/thermometer.svg
  index.html
Labels: enhancement

#32 Settings integration
  JS/loadingData.js
  JS/marker.js
  JSON/Settings.json
Labels: enhancement

#33 Graph styling
  CSS/cardstyle.css
  JS/card.js
  JS/graph.js
  SVG/person.svg
Labels: enhancement

#34 Revert "Graph styling"
  CSS/cardstyle.css
  JS/card.js
  JS/graph.js
  SVG/person.svg
Labels: bug

#40 Graph date changing
  CSS/cardstyle.css
  JS/card.js
  JS/graph.js
  JS/loadingData.js
Labels: enhancement

#41 Popup focus
  JS/graph.js
  JS/marker.js
Labels: enhancement

#45 Add title to popup
  CSS/cardstyle.css
  JS/card.js
  JS/marker.js
  JS/measurement.js
  index.html
Labels: styling
